name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: sudo apt-get install guile-3.0-dev guile-3.0 libsdl2-dev libsdl2-gfx-dev
    
    - name: autogen
      run: ./autogen.sh
      
    - name: Install dependencies
      run: make
